import { ContentItem } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Fri Mar 29 2019 09:01:58 GMT+0100 (GMT+01:00).
 */
export class CodeSamples extends ContentItem {
  public codeSamples: ContentItem[];

  constructor() {
    super({
      propertyResolver: ((fieldName: string) => {
        if (fieldName === 'code_samples') {
          return 'codeSamples';
        }
        return fieldName;
      }),
    });
  }
}
